compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "@types/react@*":
    peerDependencies:
      react: "*"
  next@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
